version: "3.3"
services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    volumes:
     - /home/athul/Documents/assessment/csvserver/solution/inputFile:/csvserver/inputdata
    environment:
     CSVSERVER_BORDER: Orange
    ports:
     - "9393:9300"
